global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'pgexporter'
    scrape_timeout: 15s
    static_configs:
      - targets: ['host.docker.internal:5002']
        labels:
          instance: 'pgexporter-local'
